version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    ports:
      - 5435:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456789'
      POSTGRES_DB: 'invest-db'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8'
      PGDATA: '/var/lib/postgresql/data/pgdata'

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d invest-db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7.2.3-alpine3.19
    ports:
      - '6379:6379'
    restart: unless-stopped
